### ISSUE TITLE
Is there a BOM?

### ISSUE THREAD

**Issue by angiamusic** [Quinienl/NanoGrids#1]
Hello,

I'm interested in making one of these myself, however I wasn't able to find the BOM. Would you happen to be able to provide one? Or is there already one and I'm just missing something?

Thank you!

**Comment by Quinienl** [comment]
Hi there,

There is a topic on muffwiggel about this module. The Bom should be in the kicad project. Kicad should be able to export this.
If you can not find the option or have trouble with it please let me know and I will send you the BOM.

Keep in mind I'm no where a real electonics engineer. so some minor mistakes could be made.
Also see the muffwiggle topic. Someone was able to build it without to much trouble.

I even think I got some of his trouble fixed before uploading it to git.

Best regards
Quinie





On Maandag 26 Oktober 2020 14:51 CET, angiamusic <notifications@github.com> wrote:
 
 
Hello,
I'm interested in making one of these myself, however I wasn't able to find the BOM. Would you happen to be able to provide one? Or is there already one and I'm just missing something?
Thank you!

**Comment by angiamusic** [comment]
Thank you for your quick reply! I was successfully able to get the BOM from the Kicad itself, still only just learning so I didn't know that was possible haha. 

Regards,
Aditya

**Comment by Quinienl** [comment]
Put some extra info on my website. BOM also ;)
http://www.quinie.nl/?p=17
