### ISSUE TITLE
.ino file?

### ISSUE THREAD

**Issue by strpstv** [Quinienl/NanoGrids#2]
Hi! i'm cuilding your nanogrids at the moment and was wonderint how you flashed the program to the microprocessor? Can't seem to find any file to load on it? thank you!

**Comment by Phipanjo** [comment]
Hi, same problem here :S Really nice module; I read on your homepage you may have some panels / PCBs at stock. May you send me one set? Of course I will pay for that :-)

**Comment by strpstv** [comment]
hey phipanjo, i succeeded mine.
You need to uplad this hex file to the nano: drive.google.com/drive/folders/0B5t7I7Q0p5bpdVEwamdscjJvdVU
i used this technique to prepare my chinese nano (but there are other ways): https://support.arduino.cc/hc/en-us/articles/360012048100-How-to-burn-the-bootloader-in-an-Arduino-Nano-using-an-Arduino-UNO
and then used this software to program the hex on it: https://www.polaxis.be/download/easyuploader-for-mac/

**Comment by Quinienl** [comment]
You can use the code by Mutable Instrument. But then you have to make your own .hex and upload it to the nano. I have not tested the hex strpstv has posted, but I did upload a hex file to my site. 

https://www.quinie.nl/nanogrids-the-hex-file/

For board I still have a few left and selling these at 15 euro's the set (panel and 2 pcb's). I have a few black and white panels remaining. You can contact me on the contact form (quinie.nl) or just email me at Qui...@Quinie.nl.

**Comment by Phipanjo** [comment]
Perfect guys, thank you!
I will order a kit these days; you'll get mail :-D
