### ISSUE TITLE
Confused about the Arduino nano version

### ISSUE THREAD

**Issue by sewtsPatrick** [Quinienl/NanoGrids#3]
The BOM on the website says nano v2.x but the filenames say gridsNanoV3. Will the files on master work für nano v3 and if not can I swap the pins anywhere in software (since nano v2 and v3 have swapped addresses for analog pins AFAIK)?

**Comment by Quinienl** [comment]
Hi sorry for the confusion. I think i used the footprint of a nano 2 in the software or something like that have to double check.
But you should install a Nano v3. 

I also have seen a version with a seeeduino 

_Quote from other builder Erik: I used the new cheaper seeeduino nano. Working perfectly!_
https://www.quinie.nl/nanogrid-gallery/ <-- last pictures

ps thanks for point out the error in the BOM updated the site

**Comment by sewtsPatrick** [comment]
@Quinienl thank you very much for your quick response and the awesome design! Can't wait to build mine :)
